Set-AzSqlDatabaseAudit -ResourceGroupName "ase-usgovvirginia-rg" -ServerName "joscot" -DatabaseName "joscot" -LogAnalyticsTargetState Enabled -WorkspaceResourceId "/subscriptions/0259b535-48b0-4b38-8a55-0e3dc4ea093f/resourceGroups/LogAnalytics-rg/providers/Microsoft.OperationalInsights/workspaces/joscot-la" `
    -AuditActionGroup "APPLICATION_ROLE_CHANGE_PASSWORD_GROUP", `
    "BACKUP_RESTORE_GROUP", `
    "DATABASE_CHANGE_GROUP", `
    "DATABASE_LOGOUT_GROUP", `
    "DATABASE_OBJECT_CHANGE_GROUP",`
    "DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP",`
    "DATABASE_OBJECT_PERMISSION_CHANGE_GROUP",`
    "DATABASE_OPERATION_GROUP",`
    "DATABASE_OWNERSHIP_CHANGE_GROUP",`
    "DATABASE_PERMISSION_CHANGE_GROUP",`
    "DATABASE_PRINCIPAL_CHANGE_GROUP",`
    "DATABASE_PRINCIPAL_IMPERSONATION_GROUP",`
    "DATABASE_ROLE_MEMBER_CHANGE_GROUP",`
    "DBCC_GROUP",`
    "FAILED_DATABASE_AUTHENTICATION_GROUP",`
    "SCHEMA_OBJECT_ACCESS_GROUP",`
    "SCHEMA_OBJECT_CHANGE_GROUP",`
    "SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP",`
    "SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP",`
    "SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP",`
    "USER_CHANGE_PASSWORD_GROUP"
